[project]
name = "python-to-the-top"
version = "0.1.0"
description = "The way to the top of Python!"
requires-python = ">=3.13"
dependencies = [
    "lxml-html-clean==0.4.2",
    "requests-html==0.10.0",
]
